dotenv: .env
dependencies:
  # - <organisation/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
networks:
  sepolia:
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
  ganache-cli:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
